# Generated by Django 4.1 on 2022-08-27 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planta',
        ),
    ]
