# Generated by Django 4.1 on 2022-08-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='preco',
            field=models.FloatField(default=1.99),
        ),
    ]
