# Generated by Django 4.1 on 2022-08-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0006_alter_planta_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='descricao',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='planta',
            name='imageurl',
            field=models.TextField(default='', max_length=500),
        ),
    ]
